### ISSUE TITLE
Cannot load distorm3 library

### ISSUE THREAD

**Issue by localacct** [anatolikalysch/VMAttack#11]
Hi

I know that a previous issue on this has been raised (#5). For my case, I did install idacute using pip
````
Requirement already satisfied: idacute in C:\Python27\lib\site-packages (1.0.1)
````

However, when I launched IDA Pro, the plugin kept stating that it could not find the module. Is there any way to resolve this?

[EDIT 6 May 2020]

I managed to resolve the issue mentioned but now I am seeing another error

````
VMAttack_plugin_stub.py: Error loading the diStorm dynamic library (or cannot load library into process).
Traceback (most recent call last):
  File "C:\Program Files (x86)\IDA 6.95\python\ida_idaapi.py", line 509, in IDAPython_ExecScript
    execfile(script, g)
  File "C:/Program Files (x86)/IDA 6.95/plugins/VMAttack_plugin_stub.py", line 14, in <module>
    plugin = imp.load_source(__name__, plugin_path)
  File "E:\vmattack\VMAttack.py", line 8, in <module>
    from static.static_deobfuscate import *
  File "E:\vmattack\static\static_deobfuscate.py", line 8, in <module>
    from lib.Instruction import Instruction
  File "E:\vmattack\lib\Instruction.py", line 6, in <module>
    import distorm3
  File "C:\Python27\lib\site-packages\distorm3\__init__.py", line 62, in <module>
    _distorm = _load_distorm()
  File "C:\Python27\lib\site-packages\distorm3\__init__.py", line 60, in _load_distorm
    raise ImportError("Error loadi
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'print_banner' is not defined
````

I also tried the modification here (https://groups.google.com/forum/#!msg/rekall-discuss/AVRub4gk0-w/BHVhkc7qJvIJ) to modify distorm3's __init__.py but it still does not work

Any advice is appreciated.

**Comment by p1x31** [comment]
Use this link to download and install[ Visual C++ 2015 Build Tools](http://go.microsoft.com/fwlink/?LinkId=691126&fixForIE=.exe.). It will automatically download visualcppbuildtools_full.exe and install Visual C++ 14.0 without actually installing Visual Studio. After the installation completes, retry pip install and you won't get the error again.
