### ISSUE TITLE
No module named cute

### ISSUE THREAD

**Issue by stonedreamforest** [anatolikalysch/VMAttack#5]
Ican't solve it ，plz help me:)
---------------------------
Warning
---------------------------
VMAttack_plugin_stub.py: No module named cute
Traceback (most recent call last):
  File "D:\Program Files (x86)\IDA 6.8\python\idaapi.py", line 601, in IDAPython_ExecScript
    execfile(script, g)
  File "D:/Program Files (x86)/IDA 6.8/plugins/VMAttack_plugin_stub.py", line 14, in <module>
    plugin = imp.load_source(__name__, plugin_path)
  File "C:\Users\Administrator\Desktop\VMAttack-master\VMAttack.py", line 7, in <module>
    from dynamic.dynamic_deobfuscate import *
  File "C:\Users\Administrator\Desktop\VMAttack-master\dynamic\dynamic_deobfuscate.py", line 7, in <module>
    from ui.UIManager import GradingViewer
  File "C:\Users\Administrator\Desktop\VMAttack-master\ui\UIManager.py", line 9, in <module>
    from cute import QtGui, QtCore, QtWidgets, form_to_widget, use_qt5
ImportError: No module named cute

---------------------------
OK   
---------------------------

**Comment by evandrix** [comment]
*bump*

**Comment by anatolikalysch** [comment]
Did you use the setup.py file for the installation? Have you tried installing idacute from pip?

**Comment by p1x31** [comment]
try copy cute from C:\Program Files\Python37\Lib\site-packages\cute to your project
C:\Users\Administrator\Desktop\VMAttack-master\ui\
